environment:
  nodejs_version: "10.9.0" # Same version as used in CircleCI.

matrix:
  fast_finish: true

skip_tags: true
skip_branch_with_pr: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@~5.6.0
  - npm install

test_script:
  - node --version
  - yarn --version
  - yarn test -- --full
  - appveyor-e2e.bat

build: off
deploy: off

cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%\\Yarn"
